version: "3.9"

services:
  pitstop_api:
    container_name: pitstop_api
    image: python:3.10
    build: .
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    command: bash -c '/app/manage.py migrate && /app/manage.py runserver 0.0.0.0:8000' 
  
  db:
    container_name: db
    image: postgres
    environment:
     - POSTGRES_USER=matheus_araujo
     - POSTGRES_PASSWORD=1234
     - POSTGRES_DB=capstone_django
    ports:
      - 5432:5432
    expose: 
      - 5432


