version: "3.9"

services:
  pitstop_api:
    container_name: pitstop_api
    build: .
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db
      - migration
  
  migration:
    build: .
    env_file: .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py migrate'
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    expose: 
      - 5432


