# Generated by Django 4.0.6 on 2022-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
