# Generated by Django 4.0.6 on 2022-07-27 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=50)),
                ('warranty', models.IntegerField()),
                ('img', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(max_length=50)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='stock.stock')),
            ],
        ),
    ]
