# Generated by Django 4.0.6 on 2022-07-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categorie',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
