# Generated by Django 4.0.6 on 2022-07-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='warrant',
            new_name='warranty',
        ),
    ]
